export const USER_OWNER = "USER-OWNER"
export const USER_ADMIN_COMPANY = "USER-COMPANY"
export const USER_ADMIN_ESTABLISHMENT = "USER-ESTABLISHMENT"
export const USER_CASHIER = "USER-CASHIER"

export const Roles = {
    USER_OWNER,
    USER_ADMIN_COMPANY,
    USER_ADMIN_ESTABLISHMENT,
    USER_CASHIER
}